[default]
RPC_URL='https://rpc.linea.build'
CHAIN_NAME='linea'
PROTOCOLS_STARTING_BLOCKS={gravita=2952006, sushiswap=3203675, connext=2954869, velocore=2999728, lynex=3460121}
BLOCKS_CSV_FILE_LOC='adapters/block_numbers.csv'

[dev]
S3_BUCKET='mode-openblocklabs-dev'
ATHENA_DATABASE='db_mode_dev'

[prod]
S3_BUCKET='mode-openblocklabs'
ATHENA_DATABASE='mode'